[android]
target_sdk_version = 33
permissions = [
    "READ_MEDIA_AUDIO",
    "READ_EXTERNAL_STORAGE",
    "WRITE_EXTERNAL_STORAGE"
]

[ios]
permissions = [
    "NSAppleMusicUsageDescription=GroovyBox needs access to your music library to play songs.",
    "NSDocumentsFolderUsageDescription=GroovyBox needs access to import music files from your documents."
]
